### ISSUE TITLE
How to catch errors

### ISSUE THREAD

**Issue by binaryape** [akash-akya/ex_cmd#17]
Hi,

I'm trying to switch from Exile to Ex_cmd. The exceptions raised by Exile when the command fails don't seem to happen the same way for ex_cmd - I get blank results and an error is logged, but I can't see how to catch an error in the external command.

Is there a way to see the return code of the command after it is run?

**Comment by akash-akya** [comment]
Hi @binaryape, can you share which error specifically you are facing issue? An example would be great.

**Comment by binaryape** [comment]
I should have done that straight away, sorry! I'll try to get an example to you tomorrow

**Comment by binaryape** [comment]
Here is a self-contained Elixir script:

```elixir
Mix.install(
  [
    {:exile, "~> 0.1.0"},
    {:ex_cmd, "~> 0.7.0"},
    {:req, "~> 0.3.3"},
    {:briefly, "~> 0.4.0"},
  ]
)

good_xml = Req.get!("http://mdq.ukfederation.org.uk/entities/https%3A%2F%2Fidp.cardiff.ac.uk%2Fshibboleth", cache: true).body

bad_stylesheet = "This is NOT an XSLT template"
good_stylesheet = """
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata">
	<xsl:param name="validUntil" required="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="/md:EntitiesDescriptor | /md:EntityDescriptor">
        <xsl:copy>
            <xsl:apply-templates select="@*"/>
			<xsl:attribute name="validUntil">
				<xsl:value-of select="$validUntil"/>
			</xsl:attribute>
            <xsl:apply-templates select="node()"/>
        </xsl:copy>
	</xsl:template>
</xsl:stylesheet>
"""

runs = [
  {"Should return data", good_stylesheet},
  {"Should return an error", bad_stylesheet}
]

Enum.map(
  runs,
  fn {title, stylesheet} ->

    IO.puts "###################################################################"
    IO.puts title

    {:ok, xml_stream} = StringIO.open(good_xml)

    {:ok, stylesheet_file} = Briefly.create()
    {:ok, fh} = File.open(stylesheet_file, [:write, :utf8])
    IO.write(fh, stylesheet)
    File.close(fh)

    command = ["xsltproc", "--nowrite", stylesheet_file, "-"]

    IO.puts "Command: #{Enum.join(command, " ")}"

    try do

      out_stream = ExCmd.stream!(
        command,
        input: IO.binstream(xml_stream, 65536),
        log: false
      )

      output = out_stream
            |> Enum.to_list()
            |> Enum.join("")

      IO.puts output

    rescue
      e -> IO.puts "FAILED!"
    end

  end
)
```

When run with  the good stylesheet the command works, and returns XML. A return code of 0 is shown in the stderr.

When run with the invalid stylesheet the return code of the command (6)  is shown in the logs but unlike Exile, it doesn't seem to trigger an exception.

This isn't urgent or critical (I was just trying various libraries while doing a spike on whether or not something is feasible) but it might be something missing from the docs that would be useful for others - I'm probably using it wrong :-)

**Comment by akash-akya** [comment]
Thanks for the detailed example. Fixed it with https://github.com/akash-akya/ex_cmd/commit/13aae3ff364d706003906a569604bd00a979d446. I missed it during the last refactoring.
