### ISSUE TITLE
simplify api

### ISSUE THREAD

**Issue by ananthakumaran** [akash-akya/ex_cmd#5]
I think the api is complicated because it tries to do two things at the same time. if we look at the typical usage of `File.stream!`, it's either used for read or write, but not both. Expecting the stream returned by ExCmd to be used for both read and write might confuse users.

```elixir
ExCmd.stream(cmd: ["ffmpeg", "-i", ".."], input: input)
```

input can be of two types,

1) it can be a enumerable `input = File.stream!('video.mkv')`
2) it can be a collectable `input = fn stream -> File.stream!('video.mkv') |> Stream.into(stream) end`

The return type of ExCmd.stream will always be output stream (enumerable).

The example can then be rewritten as

```elixir
ExCmd.stream(~w(ffmepg -i - -f mp3 -), input: File.stream!("music_video.mkv", [], 65535))
|> Stream.into(File.stream!("music.mp3"))
```

This also means we can hide the Task.async

**Comment by akash-akya** [comment]
Thank you for the suggestion.

ExCmd stream is modeled after [IO.stream](https://hexdocs.pm/elixir/IO.html#stream/2), I think the usage patterns might be similar as well, so it's trying to use an existing pattern. I wanted to implement io protocol, so one can use `IO.stream` but the io protocol seems to be unnecessarily complicated. Another reason was to avoid forcing `Task`.

anyway, agree that your approach is more readable to the user than the current implementation. will update
