### ISSUE TITLE
[Question] Is this linux only?

### ISSUE THREAD

**Issue by beardedeagle** [akash-akya/ex_cmd#9]
I've been looking for a good porcelain replacement for some time and stumbled across this. I was wondering though, is this for linux only or will it work on windows as well?

**Comment by akash-akya** [comment]
Unfortunately no. Its POSIX only. Maybe one can try to port is to windows using similar APIs.

**Comment by akash-akya** [comment]
@beardedeagle tested on Windows and it only needed minor fix. The Latest version (v0.4.1) works with windows now
